var x = 3;
var y = 10;
var z = x + y;
console.log("la suma de " +x+ " y " +y+ " es igual a: " +z+ ".");
var z = x - y;
console.log("la resta de " +x+ " menos " +y+ " es igual a: " +z+ ".");
var z = x * y;
console.log("la multiplicacion de " +x+ " por " +y+ " es igual a: " +z+ ".");
var z = x % y;
console.log("la division de " +x+ " entre " +y+ " es igual a: " +z+ ".");
var z = x ** y;
console.log("la potencia de " +x+ " elevado a " +y+ " es igual a: " +z+ ".");
var z = x++;
console.log("el incremento es " +x+ " de " +z+ ".");
var z = x--;
console.log("el decremento es " +x+ " de " +z+ ".");